Repository chryz-hub/chryz-hub.github.io, pull requests merged in 2021-05, with the labels that each got.

#162 Styled Hero Section
  index.html
  src/assets/css/global.css
  src/assets/css/styles.css
Labels: Type: Feature

#194 Fixed vision class typo
  src/assets/css/styles.css
Labels: Moderators only, Type: Bug

#189 Mobile menu
  MEMBERS.md
  index.html
  src/assets/css/styles.css
  src/assets/javascript/script.js
Labels: Status: Pending, Type: Bug
